config/routes.rb
Shuff::Application.routes.draw do
  resources :categories, :except => [ :new ] do
    resources :links, :only => [ :create, :destroy ] do
      collection do 
        get :shuffle
      end
    end
  end

  match "/shuffle/:category_id" => "links#shuffle"
  root :to => 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :links, :dependent => :destroy
  belongs_to :user

  validates :user_id, :presence => true
  validates :name, :presence => true
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :category

  validates :category_id, :presence => true
  validates :url, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authorize, :except => [ :index ]
  
  # GET /categories
  # GET /categories.xml
  def index
    if current_user.nil?
      redirect_to sign_in_path
      return 
    end
      
    @categories = current_user.categories
    @category = Category.new
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = current_user.categories.find(params[:id])
    @link = Link.new
    @link.category_id = @category

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = current_user.categories.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = current_user.categories.build(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        @categories = current_user.categories
        format.html { render "index" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
before_filter :grab_category_from_category_id

  def shuffle 
    @links = links.all

    if @links.count == 0
      redirect_to @category ? @category : root_path, :notice => "You need some links first!"
    else
      @link = @links[rand(@links.count)]
    end
  end

  def create
    @link = links.build(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to(@link.category, :notice => 'Link was successfully created.') }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { render "categories/show" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @link = links.find(params[:id])
    @category = @link.category
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(@category) }
      format.xml  { head :ok }
      format.js  
    end
  end

  private 

  def links 
    @category ? @category.links : Link
  end

  def grab_category_from_category_id
    @category = Category.find(params[:category_id]) if params[:category_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title 
    @title ? @title : ""
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div id="container"><h1>Shuff!</h1>
<ul>
<% @categories.each do |category| %>
  <% next if category.id.nil? %>
  <li>
    <%= link_to category.name, category %>
    <%= link_to '→', shuffle_category_links_path(category) %>
    <%= button_to 'x', category, { :method => :delete, :confirm => "Are you sure?" } %>
  </li>
<% end %>
</ul>

<h2>Add a new category</h2>
<%= render 'form' %>

<p><%= link_to 'Sign out', sign_out_path, :method => :delete %></p>
</div>

app/views/categories/show.html.erb
<script type="text/javascript">
$(document).ready(function() {
$("#timer").keyup(function() {
  var time = $("#timer").val();
  if (time == "") 
    return;
  var old = $("#shuffle").attr("href");
  $("#shuffle").attr("href", old.replace(/=(.*)/,"="+time)); 
});
});
</script>


<div id="container">
<p id="notice"><%= notice %></p>

<h1><%= @category.name %></h1>

<p><%= link_to 'Shuffle!', shuffle_category_links_path(@category, :timer => ""), :id => "shuffle" %> Set timer for <input type="text" size="2" id="timer" />s</p>

<ul>
<%= render @category.links %>
</ul>

<h2>Add a link</h2>
<%= render 'links/form' %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shuff <%= title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'jquery_ujs' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/links/_delete.html.erb
<% remote ||= false %>
<%= button_to 'x', category_link_path(link.category, link, {:action => :destroy}), { :method => :delete, :remote => remote, :confirm => "Are you sure you want to delete this link?" } %>

app/views/links/_form.html.erb
<%= form_for([@category, @link]) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<% if link.id %>
<li>
<%= link_to link.url, link.url %>
<%= render :partial => 'links/delete', :locals => { :link => link } %>
</li>
<% end %>

app/views/links/destroy.js.erb
window.location.replace($("#shuff").attr("href"));

app/views/links/shuffle.html.erb
<script type="text/javascript">

$(document).ready(main);

function main()
{
  var url = $("#link").text();

  if (url.match(/^(http:\/\/.*)?\/categories\/(\d+)\/links\/shuffle/) || url.match(/^(http:\/\/.*)?\/shuffle\/(\d+)/)) {
    // redirect to another shuffle, preserving timer
    if (RegExp.$2 == "<%= @link.category.id %>") return;
    if (!url.match(/timer=\d+/))
      url = url + "?timer=" + gup("timer");
    window.location.replace(url);
  } else if (url.match(/^http:\/\/(www.)?youtube.com/)) {
    // embed a youtube video

    $("#iframe").html('<div id="player"></div>');

    var tag = document.createElement('script');
    tag.src = "http://www.youtube.com/player_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  } else if (url.match(/^(javascript|j):.*/)) {
    // eval a javascript
    eval(url.slice(url.indexOf(":")+1));
  } else if (url.match(/^http:\/\//)) {
    // normal url
    $('iframe').attr('src', url);
  } else if (url.match(/^#/)) {
    // display a note
    $("#toolbar").after($("<h1>").text(url.slice(1)).addClass("note"));
  }

  resizeIframe(); 

  timer = null;

  if (gup('timer') != "") {
    var time = parseInt(gup('timer'));
    setTimer(time);
  } else {
    $("#clear-timer").hide();
  }

  $("#set-timer").blur(function() {
    if($("#set-timer").val() != "")
      setTimer(parseInt($("#set-timer").val()));
    return false;
  });

  $("#set-timer").keyup(function(e) {
    var code = (e.keyCode ? e.keyCode : e.which);
    if (code == 27) $("#set-timer").val(""); 
    if (code == 13 && $("#set-timer").val() != "")
      setTimer(parseInt($("#set-timer").val()));
    return false;
  });


  $("#clear-timer").click(function() {
     clearInterval(timer);
     $("#timer-text").text("");
     $("#set-timer").show();
     $("#clear-timer").hide();
     return false;
   }); 
}

function setTimer(time) {
   clearInterval(timer);
   $("#timer-text").text(time);
   timer = setInterval(function() { countdown(time-1); }, 1000);
   $("#set-timer").hide();
   $("#clear-timer").show();
} 

function countdown(init_time) {
  
  if ($("#timer-text").text() == "" || $("#timer-text").text() == "0") {
    $("#timer-text").text("");
    return;
  } else {
    var oldTime = parseInt($("#timer-text").text());
    if (oldTime == 1) {
      alert("Time up!");
      clearInterval(timer);
      $("#timer-text").text("");
      $("#set-timer").show();
      $("#clear-timer").hide();
    } else {
      $("#timer-text").text(oldTime - 1);
    }
  }

  var shuffurl = $("#shuff").attr("href");
  var shufftime = $("#timer-text").text() == "0" ? "" : $("#timer-text").text();
  shuffurl = shuffurl.replace(/timer=\d*/,"timer="+shufftime);
  $("#shuff").attr("href", shuffurl);
}

var getDocHeight = function(){
    return Math.max(
        $(document).height(),
        $(window).height(),
        /* For opera: */
        document.documentElement.clientHeight
    );
};



function resizeIframe()
{
  $("#iframe").height( getDocHeight() - $("#toolbar").innerHeight() );
  $("#player").height( getDocHeight() - $("#toolbar").innerHeight() );
}

$(window).resize( function() {resizeIframe();} );

function gup( name )
{
  name = name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");
  var regexS = "[\\?&]"+name+"=([^&#]*)";
  var regex = new RegExp( regexS );
  var results = regex.exec( window.location.href );
  if( results == null )
    return "";
  else
    return results[1];
}

var getYouTubeId = function(url) {
  var regex = new RegExp("v=([^&#]*)");
  var results = regex.exec(url);
  if (results == null)
    return "";
  else
    return results[1];
};

function onYouTubePlayerAPIReady() {
  var videoId = getYouTubeId($("#link").text());
  player = new YT.Player('player', {
    videoId: videoId,
    playerVars: { 'autoplay': 1 },
    events: { 'onStateChange' : onPlayerStateChange }});
}

function onPlayerStateChange(event) { 
  if (event.data == YT.PlayerState.ENDED) {

    window.location.replace($("#shuff").attr("href"));
    $("#shuff").click();
  }
}

</script>
<style text="text/css">
html {overflow: hidden;} /*we don't need any scrolls for our html */
</style>

<div id="toolbar">
  <ul id="toolbar-items">
    <li>
    <a href="<%= shuffle_category_links_path(@link.category, :timer => "") %>" id="shuff"><%= image_tag "loop_16x16.png" %></a>
    </li>
    | <li>
    <%= link_to @link.url, @link.url, :id => "link" %>
    <%= render :partial => 'delete', :locals => { :link => @link, :remote => true } %>
    </li>
    | <li>
    <%= image_tag "clock_16x16.png" %>
    <span id="timer">
      <span id="timer-text"></span>
      <input type="text" id="set-timer" size="2" /><a href="#" id="clear-timer">x</a></span>
    </li>
    | <li>
    <a href="/"><%= image_tag "home_16x16.png" %></a>
    </li>
  </ul>
</div>
<div id="iframe">
  <iframe src="" />
  </div>